// Pre-defined demo notifications — cover every category and priority level
// so the notifications page feels full and representative in demo mode.
// All keys are prefixed with 'demo_' to distinguish from real notifications.

export const DEMO_NOTIFICATIONS = [
  {
    key:       'demo_mortgage_expiry_30',
    demo:      true,
    category:  'mortgage',
    priority:  'high',
    icon:      'home',
    iconColor: '#ff4d4d',
    title:     'Fixed rate expires in 28 days',
    body:      '12 Oak Street (Halifax) fixed rate ends on 23 Jul 2026. Act now to avoid reverting to the 7.49% standard variable rate.',
    link:      '/mobile/mortgage',
    read:      false,
  },
  {
    key:       'demo_isa_95pct',
    demo:      true,
    category:  'isa',
    priority:  'high',
    icon:      'savings',
    iconColor: '#ff4d4d',
    title:     'ISA allowance almost full',
    body:      'Only £1,250 left of your £20,000 ISA allowance before April 5th — use it or lose it.',
    link:      '/mobile/savings',
    read:      false,
  },
  {
    key:       'demo_tax_year_urgent',
    demo:      true,
    category:  'milestone',
    priority:  'high',
    icon:      'event',
    iconColor: '#ff4d4d',
    title:     'Tax year ends in 10 days',
    body:      'Final chance to use this year\'s ISA allowance (£20,000) and pension contributions before April 5th.',
    link:      '/mobile/savings',
    read:      false,
  },
  {
    key:       'demo_pension_80pct',
    demo:      true,
    category:  'pension',
    priority:  'medium',
    icon:      'account_balance',
    iconColor: '#a78bfa',
    title:     'Pension allowance at 80%',
    body:      'You\'ve contributed £48,000 toward your £60,000 annual allowance — £12,000 remaining this tax year.',
    link:      '/mobile/pension',
    read:      false,
  },
  {
    key:       'demo_jisa_sophie',
    demo:      true,
    category:  'isa',
    priority:  'medium',
    icon:      'child_care',
    iconColor: '#ff9500',
    title:     'Sophie\'s JISA approaching limit',
    body:      'Sophie has contributed £7,800 of the £9,000 annual JISA limit — £1,200 remaining this tax year.',
    link:      '/mobile/family/allowances',
    read:      false,
  },
  {
    key:       'demo_ltv_75pct',
    demo:      true,
    category:  'mortgage',
    priority:  'low',
    icon:      'trending_down',
    iconColor: '#4edea3',
    title:     'LTV dropped below 75%',
    body:      '12 Oak Street is now at 74.3% LTV — you may qualify for better mortgage rates. Worth comparing deals at your next renewal.',
    link:      '/mobile/mortgage',
    read:      true,
  },
  {
    key:       'demo_net_worth_100k',
    demo:      true,
    category:  'milestone',
    priority:  'low',
    icon:      'emoji_events',
    iconColor: '#ffd700',
    title:     'Net worth reached £100,000',
    body:      'Your combined pension, savings, and property equity has passed the £100,000 mark. Keep going.',
    link:      '/mobile/dashboard',
    read:      true,
  },
];
